### ISSUE TITLE
View config not found for name input error pops out when the program is run

### ISSUE THREAD

**Issue by sudhirkumarojhaa** [jchiam/react-three-state-checkbox#2]
![screen shot 2018-05-21 at 2 48 29 pm](https://user-images.githubusercontent.com/24911219/40300185-1963dfe2-5d06-11e8-9c1e-19349b38190c.png)
`render() {
    const { checked, indeterminate } = this.state;
    return (
      <View>
      <Checkbox
        checked={checked}
        indeterminate={indeterminate}
        onChange={this.handleChange}
      />
      </View>
    );
  }`

**Comment by jchiam** [comment]
Hi there, this component was not written to support React Native.

**Comment by sudhirkumarojhaa** [comment]
Can you suggest any library for react native?

**Comment by jchiam** [comment]
I have not tried this before, but this repo seems to support checkboxes with indeterminate state as well.

https://github.com/crazycodeboy/react-native-check-box

**Comment by sudhirkumarojhaa** [comment]
Thanks for the help.
