### ISSUE TITLE
custom styling not available

### ISSUE THREAD

**Issue by arvind0364** [jchiam/react-three-state-checkbox#358]
Is there any way to style the checkbox.? I need to add custom style when the checkbox is in indeterminate state.?

**Comment by jchiam** [comment]
Custom styling is available. I've exposed `className` and `style` to the input component as props.

https://github.com/jchiam/react-three-state-checkbox/blob/master/src/Checkbox.tsx#L16-L17

**Comment by arvind0364** [comment]
but I could not change the background color of the checkbox can you guide me on this.?

**Comment by jchiam** [comment]
You may want to try reading up on this.
https://stackoverflow.com/questions/4148499/how-to-style-a-checkbox-using-css
