### ISSUE TITLE
Component doesn't seem to work in IE11

### ISSUE THREAD

**Issue by BaarishRain** [jchiam/react-three-state-checkbox#59]
In IE 11 browser, I see this error in console - SCRIPT1003: Expected ':'

Please let me know how to overcome this or if there is anything that can be done from your side.

**Comment by jchiam** [comment]
You're probably missing some polyfills. You may want to check the way you're bundling you code.

**Comment by BaarishRain** [comment]
Problem seems to be in this line for IE11.
const Checkbox = ({ checked, indeterminate = false, className = '', style = {}, disabled = false, onChange }) => {

I tried including the below line in my index.html to fix the issue. It doesn't work.
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default"></script>

Tried using below line as first line in js file. No luck.
var polyfilll = require('react-app-polyfill/ie11'); 

Also tried using these
var coreJs = require('core-js/stable');
var runtime = require('regenerator-runtime/runtime');

I don't seem to have any luck getting this fixed. I would be grateful if you can let me know what I am missing.

**Comment by jchiam** [comment]
This repo actually provides just 30 lines of code convenience. Perhaps you can just copy the source code and run it in your project. If it still doesn't work, you may want to find the right polyfills, or rewrite the component yourself.
